# Generated by Django 6.0.7 on 2026-07-25 16:59

import django.core.validators
from django.db import migrations, models


def clean_phone_numbers(apps, schema_editor):
    Farmer = apps.get_model("farmers", "Farmer")
    for farmer in Farmer.objects.exclude(phone_number=""):
        digits = "".join(ch for ch in farmer.phone_number if ch.isdigit())[:11]
        if digits != farmer.phone_number:
            Farmer.objects.filter(pk=farmer.pk).update(phone_number=digits)


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0005_farmer_remarks"),
    ]

    operations = [
        migrations.RunPython(clean_phone_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="farmer",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid PH mobile number: 11 digits, starting with 09 (e.g. 09171234567).",
                        regex=r"^09\d{9}$",
                    )
                ],
            ),
        ),
    ]
