# Generated by Django 5.2.16 on 2026-08-11 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_alter_farmer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='fca_membership',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='farmer',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_farmers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmer',
            name='philsys_pcn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='philsys_registered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='philsys_trn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='FarmerUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('SLIP_A', 'Slip A - Personal Information'), ('SLIP_B', 'Slip B - Farm Parcel Information')], max_length=10)),
                ('transaction_code', models.CharField(blank=True, max_length=80)),
                ('change_reason', models.CharField(choices=[('CORRECTION', 'A - Correction'), ('REMOVAL', 'B - Removal'), ('ADDITION', 'C - Additional / New Information'), ('OTHER', 'Other')], default='CORRECTION', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('agriculturist_name', models.CharField(blank=True, max_length=180)),
                ('snapshot_before', models.JSONField(default=dict)),
                ('snapshot_after', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_updates', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='farmers.farmer')),
            ],
            options={
                'verbose_name_plural': 'farmer update histories',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
