# Generated by Django 6.0.7 on 2026-07-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_croprecord_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croprecord',
            name='cropping_schedule',
        ),
    ]
