# Generated by Django 5.2.16 on 2026-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_remove_croprecord_cropping_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecord',
            name='cropping_schedule',
            field=models.CharField(blank=True, help_text='Official Slip B schedule, for example Jan-Mar', max_length=40),
        ),
        migrations.AddField(
            model_name='croprecord',
            name='is_intercrop',
            field=models.BooleanField(default=False),
        ),
    ]
