# Generated by Django 5.2.16 on 2026-07-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatalog',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='badge_color',
            field=models.CharField(default='#008552', max_length=7),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='icon',
            field=models.ImageField(blank=True, upload_to='service_icons/'),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='internal_remarks',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='notes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='office_responsible',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='seasonality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='target_beneficiaries',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
