# Generated by Django 5.2.16 on 2026-07-12 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ownership_type', models.CharField(choices=[('OWNED', 'Owned'), ('TENANT', 'Tenant'), ('LEASED', 'Leased'), ('ARB', 'ARB')], max_length=30)),
                ('coordinates', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='farmers.farmer')),
            ],
        ),
    ]
