# Generated by Django 6.0.7 on 2026-07-21 10:24

from django.db import migrations, models


def convert_flatland_to_upland(apps, schema_editor):
    FarmParcel = apps.get_model("farm_parcels", "FarmParcel")
    FarmParcel.objects.filter(land_type="FLATLAND").update(land_type="UPLAND")


class Migration(migrations.Migration):

    dependencies = [
        ('farm_parcels', '0004_rsbsa_parcel_fields'),
    ]

    operations = [
        migrations.RunPython(convert_flatland_to_upland, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='farmparcel',
            name='is_organic',
        ),
        migrations.AlterField(
            model_name='farmparcel',
            name='land_type',
            field=models.CharField(choices=[('UPLAND', 'Upland'), ('LOWLAND', 'Lowland')], default='UPLAND', max_length=30),
        ),
    ]
