# Generated by Django 5.2.16 on 2026-08-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_parcels', '0006_alter_farmparcel_farm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmparcel',
            name='land_type',
            field=models.CharField(choices=[('UPLAND', 'Upland'), ('LOWLAND', 'Lowland')], default='', max_length=30),
        ),
    ]
