# Generated by Django 5.2.16 on 2026-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_parcels', '0007_alter_farmparcel_land_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmparcel',
            name='gpx_status',
            field=models.CharField(choices=[('KNOWN', 'GPX / Georeference ID recorded'), ('FORGOT', 'Farmer forgot the GPX / Georeference ID'), ('NOT_GEOREFERENCED', 'Not yet georeferenced')], default='KNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='farmparcel',
            name='land_owner_rsbsa_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='farmparcel',
            name='ownership_document_other',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='farmparcel',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='farmparcel',
            name='rotational_tiller',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmparcel',
            name='farm_type',
            field=models.CharField(blank=True, choices=[('IRRIGATED', 'Irrigated'), ('RAINFED_UPLAND', 'Rainfed Upland'), ('RAINFED_LOWLAND', 'Rainfed Lowland')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='farmparcel',
            name='ownership_document',
            field=models.CharField(blank=True, choices=[('CLT', 'Certificate of Land Transfer'), ('EP', 'Emancipation Patent'), ('INDIVIDUAL_CLOA', 'Individual Certificate of Land Ownership Award (CLOA)'), ('COLLECTIVE_CLOA', 'Collective CLOA'), ('CO_OWNERSHIP_CLOA', 'Co-Ownership CLOA'), ('AGRICULTURAL_SALES_PATENT', 'Agricultural Sales Patent'), ('HOMESTEAD_PATENT', 'Homestead Patent'), ('FREE_PATENT', 'Free Patent'), ('TITLE', 'Certificate of Title / Regular Title'), ('ANCESTRAL_DOMAIN_TITLE', 'Certificate of Ancestral Domain Title'), ('ANCESTRAL_LAND_TITLE', 'Certificate of Ancestral Land Title'), ('TAX_DECLARATION', 'Tax Declaration'), ('OTHER', 'Other (for example, Barangay Certification)')], max_length=40),
        ),
    ]
