# Generated by Django 5.2.16 on 2026-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_parcels', '0008_farmparcel_gpx_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmparcel',
            name='farm_type',
            field=models.CharField(blank=True, choices=[('Irrigated', 'Irrigated'), ('Rainfed Upland', 'Rainfed Upland'), ('Rainfed Lowland', 'Rainfed Lowland')], default='', max_length=30),
        ),
    ]
