# Generated by Django 5.2.16 on 2026-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_parcels', '0009_alter_farmparcel_farm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmparcel',
            name='ownership_document',
            field=models.CharField(blank=True, choices=[('Certificate of Land Transfer', 'Certificate of Land Transfer'), ('Emancipation Patent', 'Emancipation Patent'), ('Individual CLOA', 'Individual Certificate of Land Ownership Award (CLOA)'), ('Collective CLOA', 'Collective CLOA'), ('Co-Ownership CLOA', 'Co-Ownership CLOA'), ('Agricultural Sales Patent', 'Agricultural Sales Patent'), ('Homestead Patent', 'Homestead Patent'), ('Free Patent', 'Free Patent'), ('Certificate of Title', 'Certificate of Title / Regular Title'), ('Ancestral Domain Title', 'Certificate of Ancestral Domain Title'), ('Ancestral Land Title', 'Certificate of Ancestral Land Title'), ('Tax Declaration', 'Tax Declaration'), ('OTHER', 'Other (for example, Barangay Certification)')], max_length=80),
        ),
    ]
