# Generated by Django 5.2.16 on 2026-07-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_google_sub'),
        ('authentication', '0002_promote_superusers'),
    ]

    operations = [
    ]
